### ISSUE TITLE
Using custom  Attributes does not map the names of the columns

### ISSUE THREAD

**Issue by gustavolealg** [HeadspringLabs/bulk-writer#19] opened 2017-10-23 21:21 UTC
Hi,

I am creating a small proyect that requires to import data from Excel files. I am using an extension (for the entity type) to get the properties list to help me to set the value to the property, The following is my code:
`

    public class Import : System.Attribute
    {
        public int Column { get; set; }

        public bool MapIt { get; set; } = true;

        public string ParserFunction { get; set; } = "";

        public Import(int column)
        {
            this.Column = column;
        }

        public Import(int column, string parserFunction)
        {
            this.Column = column;
            this.ParserFunction = parserFunction;
        }

        public Import(int column, bool shouldMap)
        {
            this.Column = column;
            this.MapIt = shouldMap;
        }

        public Import(int column, bool shouldMap, string parserFunction)
        {
            this.Column = column;
            this.MapIt = shouldMap;
            this.ParserFunction = parserFunction;
        }
    }

    [Table("[Cx_AG].[Temp_Aggregates_OE_Targets_LC_Data]")]
    public class zTemp_Aggregates_OE_Targets_LC_Data
    {
        [Import(1)]
        public string countryName { get; set; }
        [Import(0)]
        public int Year { get; set; }
        [Import(6, false, "GetCurrency")]
        public int CurrencyId { get; set; }
        [Import(2)]
        public decimal Scheduled_Hours { get; set; }
        [Import(3)]
        public decimal Man_Hours { get; set; }
        [Import(4)]
        public decimal Electricity_Cost { get; set; }
        [Import(5)]
        public decimal Fuel_Cost { get; set; }
        [Import(7)]
        public decimal Maintenance_Cost { get; set; }
        [Import(6)]
        public decimal Waste_And_Other_Product { get; set; }
        [Import(8)]
        public decimal By_Product { get; set; }

    }

`

The error occurs when I execute the following code:
`
                using (var bulkWriter = new BulkWriter<zTemp_Aggregates_OE_Targets_LC_Data>(connectionString))
                {
                    bulkWriter.BatchSize = 1000;
                    bulkWriter.WriteToDatabase(_data);
                }
`

I am getting the error "The given ColumnMapping does not match up with any column in the source or destination". The image below showing the piece of code where the column names is missing.

![sourcecode](https://user-images.githubusercontent.com/32648474/31912898-0d2799c6-b80b-11e7-8a05-7bbd60f9b90d.GIF)

Be aware that I must to change the following condition to get the mapping:
![sourcecode_condition](https://user-images.githubusercontent.com/32648474/31912987-6ba01528-b80b-11e7-9ebe-88580bdb86df.GIF)

I have other proyects that does not use custom attributes and they are working fine.

Thank you in advance

Gustavo Leal

**Comment by gustavolealg** [comment] 2017-10-23 21:35
Just to clarify; when BulkWrites ejecutes the line of code:  _propertyMappings = typeof(TResult).BuildMappings();

It have the list:

![image](https://user-images.githubusercontent.com/32648474/31914407-255665b8-b810-11e7-859d-d96943e070e7.png)


Thanks

**Comment by Hubert-Rybak** [comment] 2017-11-05 22:03
Duplicate of #11. Fixed in PR #21

**Closed** 2018-04-11 03:12 UTC
